type EventType =
  | 'session_launched'
  | 'commit'
  | 'pr_opened'
  | 'pr_merged'
  | 'status_updated'
  | 'pr_body_invalid'
  | 'pr_body_invalid_warning'
  | 'pr_body_updated_via_marker'
  | 'attribution_missing'
  | 'session_launch_refused_zdr'
  | 'data_residency_flag_toggled'
  | 'arch_store_adopted_toggled'
  | 'file_pollution_reverted'
  | 'file_pollution_checked'
  | 'file_pollution_re_injected_blocked'
  | 'autofix_for_ci_failure'
  | 'autofix_banned_file_unstaged'
  | 'file_pollution_check_failed'
  | 'handle_clean_exit_entered'
  | 'handle_clean_exit_session_marked_done'
  | 'handle_clean_exit_session_marked_idle'
  | 'task_orphan_reverted'
  | 'task_orphan_nudged'
  | 'task_orphan_surfaced'
  | 'task_ops_stranded_surfaced'
  | 'session_errored'
  | 'session_backfilled'
  | 'verdict_routing_failed'
  | 'manual_pr_clear'
  | 'sessions_auto_archived'
  | 'planning_sessions_idle_swept_terminal'
  | 'pr_attribution_mismatch'
  | 'pr_creation_failed'
  | 'session_aborted'
  | 'auto_launch_done_update_stuck'
  | 'auto_launch_paused'
  | 'session_marked_done_while_running'
  | 'session_done_deferred_while_running'
  | 'session_done_deferred_applied'
  | 'session_idle_write_skipped_terminal'
  | 'session_errored_write_skipped_terminal'
  | 'session_terminal_reopened'
  | 'conflict_nudge_delivery_failed'
  | 'conflict_nudge_sent'
  | 'worktree_remove_failed'
  | 'worktree_teardown_refused'
  | 'planning_session_checkout_drift'
  | 'stale_branch_abandoned'
  | 'review_side_effect_failed'
  | 'pipeline_stage_entered'
  | 'pipeline_stage_passed'
  | 'pipeline_stage_failed'
  | 'autofix_started'
  | 'autofix_complete'
  | 'pr_terminal_flags_cleared'
  | 'stalled_pr_reconcile_attempt'
  | 'stalled_pr_escalated'
  | 'stalled_pr_base_recovery_reset'
  | 'scheduled_audit_sweep_command_retry'
  | 'scheduled_audit_sweep_command_escalated'
  | 'scheduled_audit_sweep_finding_filed'
  | 'task_launch_escalated'
  | 'task_unblocked'
  | 'pr_unparked'
  | 'repo_git_config_repaired'
  | 'task_recovered'
  | 'process_fault'
  | 'process_boot'
  | 'ops_journal_state_changed'
  | 'ops_journal_entry_seeded'
  | 'ops_journal_entry_dropped'
  | 'gate_item_created'
  | 'gate_item_event_appended'
  | 'gate_item_state_changed'
  | 'gate_item_reclassified'
  | 'gate_item_source_added'
  | 'gate_item_rehomed'
  | 'gate_item_carried_forward'
  | 'seed_item_created'
  | 'seed_item_event_appended'
  | 'seed_item_state_changed'
  | 'seed_item_source_added'
  | 'seed_item_rehomed'
  | 'investigation_report_created'
  | 'investigation_report_state_changed'
  | 'task_created'
  | 'task_deps_updated'
  | 'task_body_updated'
  | 'task_type_updated'
  | 'task_properties_updated'
  | 'task_archived'
  | 'task_moved'
  | 'readiness_override'
  | 'task_deferred_blocks_dependents'
  | 'staged_intent_disposition'
  | 'staged_intent_create_supersede_noop'
  | 'capability_revoked'
  | 'capability_request_disposition'
  | 'capability_request_refused'
  | 'review_dispute_disposition'
  | 'flake_recovery_attempted'
  | 'flake_recovery_f2_invalidated'
  | 'flake_recovery_f2_rerun'
  | 'flake_recovery_analyze_invalidated'
  | 'flake_recovery_analyze_rerun'
  | 'flake_recovery_ci_rerun'
  | 'flake_recovery_exhausted'
  | 'flake_recovery_base_recovery_reset'
  | 'arch_unit_created'
  | 'arch_unit_updated'
  | 'arch_unit_superseded'
  | 'migration_reservation_reserved'
  | 'project_record_access_guide_missing'
  | 'project_record_access_guide_blocks_escalation'
  | 'flow_arm_changed'
  | 'milestone_wrapped'
  | 'base_fetch_failed'
  | 'base_fetch_ref_lock_benign'
  | 'mcp_stage_credential_rejected'
  | 'mcp_connection_established'
  | 'mcp_connection_closed'
  | 'session_mcp_unreachable_detected'
  | 'session_mcp_unreachable_respawned'
  | 'session_mcp_unreachable_respawn_exhausted'
  | 'mcp_session_credential_revoked'
  | 'route_session_credential_revoked'
  | 'route_session_credential_rejected'
  | 'session_terminated_revoked_credential'
  | 'memory_admission_deferred'
  | 'task_aborted'
  | 'planning_dispatch_launched'
  | 'capability_disposition_investigation_filed'
  | 'flaky_investigation_task_filed'
  | 'stuck_session_notify_checked'
  | 'task_display_status_changed'
  | 'stuck_session_heartbeat_tick'
  | 'session_map_entry_dropped'
  | 'planning_sessions_liveness_reconciled'
  | 'non_planning_sessions_liveness_reconciled'
  | 'orphan_processes_reaped'
  | 'staged_intent_group_committed'
  | 'manual_verification_cleared'
  | 'admission_stall_started'
  | 'admission_stall_cleared'
  | 'session_teardown_escalated'
  | 'stuck_session_alive_park_escalated'
  | 'stuck_session_pause_delivery_failed'
  | 'session_nudge_delivery_failed'
  | 'session_status_changed'
  | 'pr_state_changed'
  | 'pr_merge_state_changed'
  | 'pr_pause_reason_changed'
  | 'pr_review_result_changed'
  | 'depth_review_completed'
  | 'gate_item_schedule_changed'
  | 'gate_item_min_deployed_commit_changed'
  | 'deploy_run_status_changed'
  | 'base_health_remediation_task_filed'
  | 'no_op_investigation_skipped'
  | 'no_op_investigation_failed'
  | 'test_request_cycle_limit_crossed'
  | 'session_awaiting_operator_decision'
  | 'session_operator_decision_answered';

type ActorType = 'ai' | 'human' | 'system';

export interface AuditEvent {
  event_type: EventType;
  actor_type: ActorType;
  actor_id?: string | null;
  project_id?: string | null;
  task_id?: string | null;
  payload: Record<string, unknown>;
}

/**
 * trigger_source discriminates the two dispatch call sites so evaluator vs
 * operator activity can be told apart in the audit record — see
 * DispatchTriggerEvaluator.ts and routes/planningLaunch.ts. milestone_id is
 * always the flow_arm UUID key space (milestone.id), never gate_item's
 * display-name space.
 */
export interface PlanningDispatchLaunchedPayload {
  trigger_source: 'evaluator' | 'operator';
  flow: string;
  milestone_id: string;
}
