import path from 'node:path';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import { logger } from '../logger';
import { getSession } from '../db/queries';
import {
  insertPlanningCheckoutLock,
  deletePlanningCheckoutLock,
  getPlanningCheckoutLock,
  countPlanningCheckoutLocks,
  getAllPlanningCheckoutLocks,
} from '../db/queries';

/**
 * Planning sessions (groom/design/ops/split) share `cwd` === the project
 * checkout across concurrent sessions. This module reference-counts a
 * lockdown over that checkout (DB-backed, see planning_checkout_locks) so
 * the first concurrent planning session locks it and only the last one to
 * end unlocks it — with a carved-out writable scratch dir per session.
 *
 * Four subdirectories of the checkout are never touched by the lockdown
 * walk: `.claude/worktrees` (independent per-session coding worktrees, which
 * need their own write access regardless of any planning session sharing the
 * project's root cwd), `.claude/scratch` (this module's own writable
 * exception area), `.claude/session-prompts` (the launcher's own
 * per-session control-plane files — writeMcpConfig/writeSystemPromptFile —
 * which every session, not just planning ones, must be able to write in
 * order to even start), and `node_modules` (regenerated by the dependency
 * install on every deploy, not source of truth for anything, and the bulk —
 * ~74% — of the walk's entries; locking it also breaks a concurrent
 * dependency install).
 *
 * The walk itself uses the async fs API and is awaited by its callers rather
 * than run synchronously, so it no longer stalls the shared event loop
 * (HTTP/WebSocket/scheduler) for the duration of the traversal.
 */

const TERMINAL_STATUSES = new Set(['done', 'error', 'killed']);

function scratchRoot(projectDir: string): string {
  return path.join(projectDir, '.claude', 'scratch');
}

function worktreesRoot(projectDir: string): string {
  return path.join(projectDir, '.claude', 'worktrees');
}

function sessionPromptsRoot(projectDir: string): string {
  return path.join(projectDir, '.claude', 'session-prompts');
}

function nodeModulesRoot(projectDir: string): string {
  return path.join(projectDir, 'node_modules');
}

/**
 * Paths excluded from the lockdown walk in both directions (strip and
 * restore) — the single source of truth both call sites share, so they
 * cannot drift apart. Exported for the checkoutLockdown.test.ts drift guard.
 */
export function lockdownExcludes(projectDir: string): string[] {
  return [
    scratchRoot(projectDir),
    worktreesRoot(projectDir),
    sessionPromptsRoot(projectDir),
    nodeModulesRoot(projectDir),
  ];
}

export function getScratchDir(projectDir: string, sessionId: string): string {
  return path.join(scratchRoot(projectDir), sessionId);
}

/**
 * Recursively walks `root`, invoking `apply(currentMode)` on every entry not
 * under `excludes`. Uses the promise-based fs API so the traversal yields to
 * the event loop between entries instead of blocking it for the whole walk.
 */
async function walkAndChmod(
  root: string,
  excludes: string[],
  apply: (mode: number) => number,
): Promise<void> {
  const resolvedExcludes = excludes.map((p) => path.resolve(p));

  async function walk(p: string): Promise<void> {
    if (resolvedExcludes.includes(path.resolve(p))) return;
    let st: fs.Stats;
    try {
      st = await fsp.lstat(p);
    } catch {
      return;
    }
    // Never chase symlinks — chmod would follow them outside the checkout.
    if (st.isSymbolicLink()) return;
    try {
      await fsp.chmod(p, apply(st.mode));
    } catch (err) {
      logger.warn(`[checkoutLockdown] chmod failed for ${p}: ${err}`);
    }
    if (st.isDirectory()) {
      let entries: string[];
      try {
        entries = await fsp.readdir(p);
      } catch {
        return;
      }
      for (const entry of entries) await walk(path.join(p, entry));
    }
  }

  await walk(root);
}

/**
 * Strips all write bits (owner/group/other) from every file and directory
 * under `projectDir`, excluding `.claude/worktrees` and `.claude/scratch`.
 * `.git` is included in the walk — verified (see
 * checkoutLockdown.test.ts's "read-only .git allowlist verification" suite,
 * which runs each command for real against a fully read-only repo) that
 * none of the planning read-only Bash allowlist (log/diff/show/status/
 * blame/ls-files/rev-parse) requires a durable write to function, so no
 * path under `.git` needs a carve-out.
 */
async function stripWriteRecursive(projectDir: string): Promise<void> {
  await walkAndChmod(
    projectDir,
    lockdownExcludes(projectDir),
    (mode) => mode & ~0o222,
  );
  logger.info(`[checkoutLockdown] locked down checkout: ${projectDir}`);
}

/**
 * Restores owner write access under `projectDir`. Only the owner-write bit
 * is restored (group/other write bits, if a checkout somehow had any, are
 * not) — a solo-owned orchestrator checkout never had them to begin with.
 *
 * The excluded roots themselves are also given a shallow, idempotent
 * owner-write restore (not a recursive walk of their contents). In steady
 * state this is a no-op: the launcher always creates/writes under them
 * before any strip ever walks the tree. Its only real effect is defensive —
 * repairing an excluded root that was left read-only by a lock acquired
 * before this exclusion existed.
 */
async function restoreWriteRecursive(projectDir: string): Promise<void> {
  const excludes = lockdownExcludes(projectDir);
  await walkAndChmod(projectDir, excludes, (mode) => mode | 0o200);
  for (const dir of excludes) {
    try {
      const st = await fsp.lstat(dir);
      await fsp.chmod(dir, st.mode | 0o200);
    } catch {
      // Doesn't exist yet — nothing to restore.
    }
  }
  logger.info(`[checkoutLockdown] lifted checkout lockdown: ${projectDir}`);
}

function createScratchDir(projectDir: string, sessionId: string): string {
  const scratchDir = getScratchDir(projectDir, sessionId);
  fs.mkdirSync(scratchDir, { recursive: true });
  fs.chmodSync(scratchDir, 0o755);
  return scratchDir;
}

function removeScratchDir(scratchDir: string): void {
  try {
    fs.rmSync(scratchDir, { recursive: true, force: true });
  } catch (err) {
    logger.warn(
      `[checkoutLockdown] failed to remove scratch dir ${scratchDir}: ${err}`,
    );
  }
}

/**
 * Serializes strip/restore transitions per project dir. The walk is now
 * async (it awaits between fs calls), so without this, an acquire and a
 * release racing on the same checkout could interleave their walks and
 * leave the tree in a half-stripped/half-restored state, or run two walks
 * over each other. Ref-count bookkeeping (insert/delete/count) is still
 * synchronous DB access, so only the walk itself needs to be queued.
 */
const projectDirQueues = new Map<string, Promise<unknown>>();

function runExclusive<T>(
  projectDir: string,
  task: () => Promise<T>,
): Promise<T> {
  const key = path.resolve(projectDir);
  const prior = projectDirQueues.get(key) ?? Promise.resolve();
  const run = prior.then(task, task);
  projectDirQueues.set(
    key,
    run.then(
      () => undefined,
      () => undefined,
    ),
  );
  return run;
}

export interface CheckoutLockdownOptions {
  /**
   * Whether to strip filesystem write permission from the checkout itself.
   * CLI-mode sessions rely on this (no directory sandbox of their own).
   * Docker-mode sessions instead get a read-only bind mount at the runner
   * level, so this should be false there — the OS-level chmod would be
   * redundant (and would need lifting again on the host regardless of
   * container lifecycle).
   */
  applyFsLockdown: boolean;
}

/**
 * Acquires the checkout lockdown for a planning session: creates its
 * writable scratch dir, records it in the ref-counted DB table, and — if
 * this is the first concurrent lock and `applyFsLockdown` is set — strips
 * write permission from the rest of the checkout.
 *
 * Returns the session's scratch dir path.
 */
export async function acquireCheckoutLockdown(
  projectDir: string,
  sessionId: string,
  options: CheckoutLockdownOptions,
): Promise<string> {
  const scratchDir = createScratchDir(projectDir, sessionId);
  insertPlanningCheckoutLock(sessionId, projectDir, scratchDir);

  const count = countPlanningCheckoutLocks(projectDir);
  if (options.applyFsLockdown && count === 1) {
    await runExclusive(projectDir, () => stripWriteRecursive(projectDir));
  }

  return scratchDir;
}

/**
 * Releases the checkout lockdown held by `sessionId` (no-op if it never
 * held one — e.g. non-planning sessions, or already released): removes its
 * scratch dir, drops the DB row, and — if this was the last concurrent
 * planning session on that checkout — lifts the lockdown.
 */
export async function releaseCheckoutLockdown(
  sessionId: string,
  options: CheckoutLockdownOptions,
): Promise<void> {
  const row = getPlanningCheckoutLock(sessionId);
  if (!row) return;

  removeScratchDir(row.scratch_dir);
  deletePlanningCheckoutLock(sessionId);

  const count = countPlanningCheckoutLocks(row.project_dir);
  if (options.applyFsLockdown && count === 0) {
    await runExclusive(row.project_dir, () =>
      restoreWriteRecursive(row.project_dir),
    );
  }
}

/**
 * Boot-time reconciliation: prunes lock rows for sessions that are terminal
 * (or gone entirely — process died before it could release) and restores
 * each touched project's filesystem state to match its post-prune ref
 * count. Idempotent — safe to run even when nothing crashed mid-transition.
 */
export async function reconcileCheckoutLockdownAtBoot(options: {
  applyFsLockdown: boolean;
}): Promise<void> {
  const rows = getAllPlanningCheckoutLocks();
  const touchedDirs = new Set(rows.map((r) => r.project_dir));

  for (const row of rows) {
    const session = getSession(row.session_id);
    const isTerminal = !session || TERMINAL_STATUSES.has(session.status);
    if (!isTerminal) continue;

    logger.info(
      `[checkoutLockdown] boot reconciliation: pruning stale lock for session ${row.session_id.slice(0, 8)}`,
    );
    removeScratchDir(row.scratch_dir);
    deletePlanningCheckoutLock(row.session_id);
  }

  for (const projectDir of touchedDirs) {
    const count = countPlanningCheckoutLocks(projectDir);
    if (!options.applyFsLockdown) continue;
    if (count > 0) {
      await runExclusive(projectDir, () => stripWriteRecursive(projectDir));
    } else {
      await runExclusive(projectDir, () => restoreWriteRecursive(projectDir));
    }
  }
}
